AWSTemplateFormatVersion: '2010-09-09'
Description: 'AuditIQ Infrastructure Stack'

Resources:
  AuditIQBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: auditiq-documents
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  AuditIQDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: auditiq-mysql
      Engine: mysql
      EngineVersion: '8.0'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: admin
      MasterUserPassword: !Ref DBPassword
      DBName: auditiq_db

Parameters:
  DBPassword:
    Type: String
    NoEcho: true
    Description: Database password
